language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

#install:
#  - wget https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7.1.tar.gz?raw=true --output-document=cpputest-3.7.1.tar.gz
#  - tar -xzf cpputest-3.7.1.tar.gz
#  - pushd cpputest-3.7.1/build && autoreconf .. -i && ../configure --prefix=$HOME/cpputest && make && make install
#  - export CPPUTEST_HOME=$HOME/cpputest
#  - popd
#  - sudo apt-get install lcov

script:
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./bin/dotest

notifications:
  webhooks:
      urls:
          - https://webhooks.gitter.im/e/6de15e574ba6be5f3b79
      on_success: change
      on_failure: always

